package com.pedropathing.paths.curves.bezier;
import static com.pedropathing.utils.Utils.clamp;

import com.pedropathing.math.Matrix;
import com.pedropathing.math.Pose;
import com.pedropathing.math.Vector;
import com.pedropathing.math.Vector2D;
import com.pedropathing.paths.curves.Curve;
import com.pedropathing.paths.tvalue.TValue;
import com.pedropathing.utils.BijectiveMap;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

/**
 * This is the BezierCurve class. This class handles the creation of Bezier curves, which are used
 * as the basis of the path for the Path class. Bezier curves are parametric curves defined by a set
 * of control points. So, they take in one input, t, that ranges from [0, 1] and that returns a point
 * on the curve. Essentially, Bezier curves are a way of defining a parametric line easily. You can
 * read more on Bezier curves here: <a href="https://en.wikipedia.org/wiki/Bézier_curve">...</a>
 *
 * @author Anyi Lin - 10158 Scott's Bots
 * @author Aaron Yang - 10158 Scott's Bots
 * @author Harrison Womack - 10158 Scott's Bots
 * @author William Phomphakdee - 7462 Not to Scale Alumni
 * @version 1.0, 3/5/2024
 */
public class BezierCurve implements Curve {
    private ArrayList<Vector2D> controlPoints;
    protected final int APPROXIMATION_STEPS = 1000;
    protected final int SEARCH_LIMIT = 10;
    private double length;
    private Matrix cachedMatrix;
    private int[][] diffPowers;
    private int[][] diffCoefficients;
    protected BijectiveMap completionMap = new BijectiveMap();

    /**
     * This is the default constructor for the BezierCurve class. It initializes an empty BezierCurve.
     * This is not recommended to use, as it does not set any control points or path constraints.
     */
    public BezierCurve() {}

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(List<Vector2D> controlPoints) {
        if (controlPoints.size()<3) {
            throw new IllegalArgumentException("Too few control points");
        }

        this.controlPoints = new ArrayList<>(controlPoints);
        initialize();
    }

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(Pose... controlPoints) {
        this(Arrays.stream(controlPoints).map(Pose::toVector2D).collect(Collectors.toCollection(ArrayList::new)));
    }

    /**
     * This constructor creates a BezierCurve with the specified control points and path constraints.
     * @param controlPoints the control points for the BezierCurve, which must be at least 3 points.
     */
    public BezierCurve(Vector2D... controlPoints) {
        this(new ArrayList<>(Arrays.asList(controlPoints)));
    }

    /**
     * This handles most of the initialization of the BezierCurve that is called from the constructor.
     */
    private void initialize() {
        generateBezierCurve();
        length = approximateLength();
    }

    /**
     * This generates the Bezier curve. It assumes that the ArrayList of control points has been set.
     * This caches the matrix generated by multiplying the characteristic matrix and the matrix where each control
     * point is a row vector.
     */
    private void generateBezierCurve() {
        double[][] controlPointMatrix = new double[this.controlPoints.size()][2];
        for (int i = 0; i < this.controlPoints.size(); i++) {
            Vector2D p = controlPoints.get(i);
            controlPointMatrix[i] = new double[]{p.x(), p.y()};
        }
        Matrix controlMatrix = new Matrix(controlPointMatrix);
        cachedMatrix = CharacteristicMatrixSupplier.getBezierCharacteristicMatrix(this.controlPoints.size() - 1).times(controlMatrix);
        diffPowers = initializeDegreeArray(controlPoints.size() - 1);
        diffCoefficients = initializeCoefficientArray(diffPowers, controlPoints.size() - 1);
    }

    /**
     * This approximates the length of the BezierCurve in APPROXIMATION_STEPS number of steps. It's
     * like a Riemann's sum, but for a parametric function's arc length.
     *
     * @return returns the approximated length of the BezierCurve.
     */
    private double approximateLength() {
        Vector2D previousPoint = get(0);
        Vector2D currentPoint;
        double approxLength = 0;
        for (int i = 1; i <= APPROXIMATION_STEPS; i++) {
            double t = i/(double)APPROXIMATION_STEPS;
            currentPoint = get(t);
            approxLength += previousPoint.distance(currentPoint);
            previousPoint = currentPoint;
            completionMap.put(t, approxLength);
        }
        return approxLength;
    }

    /**
     * Initializes the degree/power array (for later processing) and cache them
     */
    private static int[][] initializeDegreeArray(int deg) {
        int[][] diffPowers = new int[3][deg + 1];

        for (int i = 0; i < diffPowers.length; i++) {
            diffPowers[i] = BezierCurve.genDiff(deg, i);
        }

        return diffPowers;
    }

    /**
     * Generate and return a polynomial's powers at the differentiation level
     * @param deg degree of poly
     * @param diffLevel number of differentiations
     * @return powers of each term in integers
     */
    private static int[] genDiff(int deg, int diffLevel){
        int[] output = new int[deg + 1];

        for (int i = diffLevel; i < output.length; i++) {
            output[i] = i - diffLevel;
        }

        return output;
    }

    /**
     * Initializes the coefficient array (for later processing) and cache them.
     * Each row is a different level of differentiation.
     */
    private static int[][] initializeCoefficientArray(int[][] diffPowers, int deg) {
        int[][] diffCoefficients = new int[3][deg + 1];

        Arrays.fill(diffCoefficients[0], 1);

        for (int row = 1; row < diffCoefficients.length; row++) {
            for (int col = 0; col < diffCoefficients[0].length; col++) {
                diffCoefficients[row][col] = diffCoefficients[row - 1][col] * diffPowers[row - 1][col];
            }
        }

        return diffCoefficients;
    }

    /**
     * This method gets the t-vector at the specified differentiation level.
     * @param t t value of the parametric curve; [0, 1]
     * @param diffLevel specifies how many differentiations are done
     * @return t vector
     */
    public Vector getTVector(@TValue double t, int diffLevel) {
        if (diffLevel == 0) return getTVector(t);
        int[] degrees = this.diffPowers[diffLevel];
        double[] powers = new double[this.controlPoints.size()];

        powers[0] = 1;
        for (int i = 1; i < powers.length; i++) {
            powers[i] = t * powers[i - 1];
        }

        double[] output = new double[powers.length];

        for (int i = 0; i < degrees.length; i++) {
            output[i] = powers[degrees[i]] * this.diffCoefficients[diffLevel][i];
        }

        return new Vector(output);
    }

    private static Vector getTVector(int[][] diffPowers, int[][] diffCoefficients, @TValue double t, int diffLevel) {
        if (diffLevel == 0) return getTVector(diffCoefficients[0].length, t);
        int[] degrees = diffPowers[diffLevel];
        double[] powers = new double[diffCoefficients[0].length];

        powers[0] = 1;
        for (int i = 1; i < powers.length; i++) {
            powers[i] = t * powers[i - 1];
        }

        double[] output = new double[powers.length];

        for (int i = 0; i < degrees.length; i++) {
            output[i] = powers[degrees[i]] * diffCoefficients[diffLevel][i];
        }

        return new Vector(output);
    }

    public Vector getTVector(@TValue double t) {
        double[] output = new double[controlPoints.size()];

        for (int i = 0; i < output.length; i++) {
            output[i] = Math.pow(t, i);
        }

        return new Vector(output);
    }

    private static Vector getTVector(int size, @TValue double t) {
        double[] output = new double[size];

        for (int i = 0; i < output.length; i++) {
            output[i] = Math.pow(t, i);
        }

        return new Vector(output);
    }

    /**
     * This returns the point on the Bezier curve that is specified by the parametric t value. A
     * Bezier curve is a parametric function that returns points along it with t ranging from [0, 1],
     * with 0 being the beginning of the curve and 1 being at the end. The Follower will follow
     * BezierCurves from 0 to 1, in terms of t.
     *
     * @param t this is the t value of the parametric curve. t is clamped to be between 0 and 1 inclusive.
     * @return this returns the point requested.
     */
    @Override
    public Vector2D get(@TValue double t) {
        return getDerivative(0, t);
    }

    @Override
    public double closestT(Vector2D position, double initialGuess) {
        double[] searchEstimates = new double[]{0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, initialGuess};
        double closestDist = 1e9;
        double bestGuess = 0;

        for (double t : searchEstimates) {
            double dist = get(t).distanceSquared(position);

            if (dist < closestDist) {
                closestDist = dist;
                bestGuess = t;
            }
        }

        initialGuess = bestGuess;

        for (int i = 0; i < SEARCH_LIMIT; i++) {
            Matrix pointAtT = Matrix.fromRows(getTVector(initialGuess, 0), getTVector(initialGuess, 1),
                    getTVector(initialGuess, 2));;
            Vector2D lastPos = Vector2D.cartesian(pointAtT.get(0, 0), pointAtT.get(0, 1));
            Vector resultant = pointAtT.times(lastPos.minus(position).toVector());

            double firstDerivative = 2 * resultant.get(1);
            double secondDerivative = 2 * (resultant.get(2) + (pointAtT.get(1, 0) * pointAtT.get(1, 0) + (pointAtT.get(1, 1) * pointAtT.get(1, 1))));

            initialGuess = clamp(initialGuess - firstDerivative / (secondDerivative + 1e-9), 0, 1);
            if (get(initialGuess).distance(lastPos) < 0.1) break;
        }

        return initialGuess;
    }

    public Vector2D getDerivative(int n, @TValue double t) {
        Vector outVel = cachedMatrix.times(getTVector(t, n));
        return Vector2D.cartesian(outVel.get(0), outVel.get(1));
    }

    /**
     * This returns the derivative on the BezierCurve that is specified by the parametric t value.
     * This is returned as a Vector2D, and this Vector2D is the tangent to the BezierCurve.
     *
     * @param t this is the t value of the parametric curve. t is clamped to be between 0 and 1 inclusive.
     * @return this returns the derivative requested.
     */
    public Vector2D derivative(@TValue double t) {
        return getDerivative(1, t);
    }

    /**
     * Returns the ArrayList of control points for this BezierCurve.
     *
     * @return This returns the control points.
     */
    public ArrayList<Vector2D> getControlPoints() {
        return controlPoints;
    }

    /**
     * Returns the approximate length of this BezierCurve.
     *
     * @return This returns the length.
     */
    public double length() {
        return length;
    }

    @Override
    public double remainingDistance(double t) {
        return (1 - getPathCompletion(t)) * length;
    }

    @Override
    public double curvature(double t) {
        Vector2D derivative = derivative(t);
        Vector2D secondDerivative = getDerivative(2, t);
        double derivMag = derivative.magnitude();

        if (derivMag < 1e-9) return 0;
        return (derivative.det(secondDerivative)) / Math.pow(derivMag, 3);
    }

    /**
     * Returns the path completion at a given t value.
     * This is used to get the percentage of the path that has been completed.
     *
     * @param t the t value of the parametric curve; [0, 1]
     * @return returns the path completion as a decimal on the range [0,1].
     */
    public double getPathCompletion(double t) {
        if (length == 0) return 0.0;
        return completionMap.interpolateKey(t) / length;
    }

    /**
     * Returns the t value corresponding to a given path completion percentage.
     * @param pathCompletion the path completion percentage; [0, 1]
     * @return returns the t value corresponding to the path completion percentage.
     */
    @Override
    public double getT(double pathCompletion) {
        return completionMap.interpolateValue(pathCompletion);
    }

    /**
     * Generates a BezierCurve that passes through the given points
     * @param startPoint the initial point the curve passes through
     * @param midpoint a point in the middle for the curve to pass through
     * @param endPoint the final point the curve passes through
     * @return the BezierCurve passing through the points
     */
    public static BezierCurve through(Pose startPoint, Pose midpoint, Pose endPoint) {
        double cx = 2 * midpoint.x() - (startPoint.x() + endPoint.x()) / 2.0;
        double cy = 2 * midpoint.y() - (startPoint.y() + endPoint.y()) / 2.0;
        Pose controlPoint = new Pose(cx, cy);
        return new BezierCurve(startPoint, controlPoint, endPoint);
    }

    /**
     * Generates a BezierCurve that passes through the given points
     * @param startPoint the first point the curve passes through
     * @param midPoint1 the second point the curve passes through
     * @param midPoint2 the third point the curve passes through
     * @param endPoint the fourth point the curve passes through
     * @return the BezierCurve passing through the points
     */
    public static BezierCurve through(Pose startPoint, Pose midPoint1, Pose midPoint2, Pose endPoint) {
        double distance1 = Math.pow(midPoint1.distance(startPoint), 0.5);
        double distance2 = Math.pow(midPoint2.distance(midPoint1), 0.5);
        double distance3 = Math.pow(endPoint.distance(midPoint2), 0.5);
        double sqDistance1 = distance1 * distance1;
        double sqDistance2 = distance2 * distance2;
        double sqDistance3 = distance3 * distance3;
        double t1 = (2 * distance1 * distance1) + (3 * distance1 * distance2) + (distance2 * distance2);
        double t2 = 3 * distance1 * (distance1 + distance2);
        double t3 = (2 * distance3 * distance3) + (3 * distance3 * distance2) + (distance2 * distance2);
        double t4 = 3 * distance3 * (distance3 + distance2);

        Pose controlPoint1 = new Pose((sqDistance1 * midPoint2.x() - sqDistance2 * startPoint.x() + t1 * midPoint1.x()) / t2,
                (sqDistance1 * midPoint2.y() - sqDistance2 * startPoint.y() + t1 * midPoint1.y()) / t2);
        Pose controlPoint2 = new Pose((sqDistance3 * midPoint1.x() - sqDistance2 * endPoint.x() + t3 * midPoint2.x()) / t4,
                (sqDistance3 * midPoint1.y() - sqDistance2 * endPoint.y() + t3 * midPoint2.y()) / t4);

        return new BezierCurve(startPoint, controlPoint1, controlPoint2, endPoint);
    }

    /**
     * Generates a BezierCurve that passes through the given points
     * @param points vararg of points; requirements more than two points
     * @return the BezierCurve passing through the points
     */
    public static BezierCurve through(Pose... points){
        double[] tValues = new double[points.length];
        tValues[points.length - 1] = 1;
        double increment = 1d / (points.length - 1);

        for (int i = 1; i < tValues.length - 1; i++) {
            tValues[i] = tValues[i - 1] + increment;
        }

        double[][] tMatrix = new double[points.length][points.length];
        for (int i = 0; i < tMatrix.length; i++) {
            tMatrix[i] = getTVector(points.length, tValues[i]).elements();
        }

        Matrix bezier = CharacteristicMatrixSupplier.getBezierCharacteristicMatrix(points.length - 1);

        double[][] targetPointMatrix = new double[points.length][2];
        for (int i = 0; i < points.length; i++) {
            targetPointMatrix[i] = new double[] {points[i].x(), points[i].y()};
        }

        Matrix coefficients = new Matrix(tMatrix).times(bezier);
        Matrix outputControlPoints = coefficients.invert().times(new Matrix(targetPointMatrix));
        Pose[] output = new Pose[points.length];

        for (int i = 0; i < outputControlPoints.rows; i++) {
            output[i] = new Pose(outputControlPoints.get(i, 0), outputControlPoints.get(i, 1));
        }

        return new BezierCurve(output);
    }
}